name: theKeyboardEditor
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux-web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Get Kha Dependencies
        run: ./Kha/get_dlc

      - name: Compile for Web
        run: node Kha/make html5

      - name: Install dependencies for Linux compilation
        run: sudo apt install -y make g++ libwayland-bin wayland-protocols libxkbcommon-dev libegl1-mesa-dev libxinerama-dev libxrandr-dev libasound2-dev libxi-dev mesa-common-dev libgl-dev libxcursor-dev libvulkan-dev libudev-dev

      - name: Compile for Linux
        run: node Kha/make --compile -g opengl

      - name: Deploy builds
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: "github.event_name == 'push'"
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/html5/ # The folder the action should deploy.

      - uses: actions/upload-artifact@v2
        if: "github.event_name == 'push'"
        with:
          name: linux
          path: build/linux-build/Release/

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Compile for Windows
        run: node Kha/make -g direct3d12 -v vs2017

      - name: Deploy build
        uses: actions/upload-artifact@v2
        if: "github.event_name == 'push'"
        with:
          name: windows
          path: build/

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Compile for macOS
        run: node Kha/make --compile

      - name: Deploy build
        uses: actions/upload-artifact@v2
        if: "github.event_name == 'push'"
        with:
          name: macos
          path: build/osx-build/build/Release/
